# Generated by Django 5.1.4 on 2024-12-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
    ]
