# Generated by Django 5.1.4 on 2024-12-30 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='ia_used',
            field=models.CharField(choices=[('GPT', 'GPT'), ('Llama', 'Llama'), ('Gemini', 'Gemini')], default='GPT', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='Nova Conversa', max_length=100),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['user', 'timestamp'], name='usuarios_ch_user_id_887528_idx'),
        ),
    ]
