# Generated by Django 5.1.4 on 2025-01-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customuser_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ do usuário (opcional).', max_length=18, null=True, unique=True),
        ),
    ]
