# Generated by Django 5.1.4 on 2024-12-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_chathistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='ia_used',
            field=models.CharField(choices=[('GPT', 'GPT'), ('Gemini', 'Gemini')], default='GPT', max_length=10),
        ),
    ]
