# Generated by Django 5.1.4 on 2025-01-22 20:17

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=usuarios.models.user_profile_picture_path),
        ),
    ]
