# Generated by Django 5.1.4 on 2024-12-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_chathistory_ia_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='ia_used',
            field=models.CharField(choices=[('GPT', 'GPT'), ('LlAMA', 'LlAMA '), ('Gemini', 'Gemini')], default='GPT', max_length=10),
        ),
    ]
