# Generated by Django 5.1.4 on 2025-01-24 17:28

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ do usuário (opcional).', max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Foto do perfil do usuário.', null=True, upload_to=usuarios.models.user_profile_picture_path),
        ),
    ]
