# Generated by Django 5.1.4 on 2025-01-23 19:34

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Foto do perfil do usuário.', null=True, upload_to=usuarios.models.user_profile_picture_path),
        ),
    ]
