# Generated by Django 5.1.4 on 2025-01-24 21:01

import usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ do usuário (opcional).', max_length=18, null=True, unique=True, validators=[usuarios.validators.validar_cnpj_existente]),
        ),
    ]
