# Generated by Django 5.1.4 on 2024-12-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_chathistory_ia_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='ia_used',
            field=models.CharField(choices=[('GPT', 'GPT'), ('Llama', 'Llama'), ('Gemini', 'Gemini')], default='GPT', max_length=50),
        ),
    ]
