# Generated by Django 5.1.4 on 2025-01-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_passwordresetcode_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Email Obrigatório.', max_length=254, unique=True),
        ),
    ]
