# Generated by Django 5.1.4 on 2025-03-06 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_especialidade_ativo_especialidade_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloManutencao',
            fields=[
                ('cod_ciclo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('intervalo', models.IntegerField()),
                ('tipo_intervalo', models.CharField(choices=[('D', 'Dias'), ('S', 'Semanas'), ('M', 'Meses'), ('A', 'Anos')], max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='usuarios.categoria')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='usuarios.especialidade')),
            ],
        ),
        migrations.DeleteModel(
            name='CicloPadrao',
        ),
    ]
