# Generated by Django 5.1.4 on 2025-03-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_ciclomanutencao_delete_ciclopadrao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matrizpadraoatividade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matrizpadraoatividade',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matrizpadraoatividade',
            name='cod_atividade',
            field=models.CharField(default='ATIVIDADE_DEFAULT', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matrizpadraoatividade',
            name='cod_centro_trab',
            field=models.CharField(default='CENTRO_ATIVIDADE_DEFAULT', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matrizpadraoatividade',
            name='cod_matriz',
            field=models.CharField(default='COD_MATRIZ_DEFAULT', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='matrizpadraoatividade',
            unique_together={('cod_matriz', 'cod_atividade')},
        ),
    ]
