# Generated by Django 5.1.4 on 2025-03-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_matrizpadraoatividade_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
